easy_admin:
  entities:
    - App\Entity\Users
    - App\Entity\Medecin
    - App\Entity\Patient
    - App\Entity\Specialite
    - App\Entity\Contact
    - App\Entity\Date
    - App\Entity\Fiche
    - App\Entity\RendezVous

  site_name: 'Rendez Vous'